"""Initial commit

Revision ID: 65629c73d1dc
Revises: 
Create Date: 2025-09-14 14:00:35.192896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65629c73d1dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('short_url', sa.String(length=18), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_shortner')
    # ### end Alembic commands ###
