apiVersion: v1
kind: job
metadata:
  name: url-shortner-migrate-job
spec:
  template:
    spec:
      restartPolicy: onFailure
      containers:
      - image: localhost:9010/url-shotner:0.0.1-alpha.65
        name: migrate
        ports:
          - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis
          - name: MYSQL_HOST
            value: mysql
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.app.deploy.otel_endpoint }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              flask db upgrade
        resources: {}  