apiVersion: batch/v1
kind: Job
metadata:
  name: url-shortner-migrate-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: localhost:9010/url-shotner:0.1.0-otel-uat.1-116
        ports:
          - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis
          - name: MYSQL_HOST
            value: mysql
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for MySQL..."
            while ! nc -vz mysql 3306 >/dev/null 2>&1; do
              echo "MySQL not ready, sleeping 5s..."
              sleep 5
            done
            echo "MySQL is ready!"
            flask db upgrade
        resources: {}
