apiVersion: v1
kind: Service
metadata:
  name: loki-querier
  namespace: logging
spec:
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: querier
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP

