name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - uat
  

jobs:
  ci-pipeline:
    name: CI Pipline
    runs-on: [self-hosted, Linux, X64, nk-wsl]
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # - name: Install Dependencies
    #   shell: bash
    #   run: |
    #     git config --global --add safe.directory '/mnt/d/actions-runner/_work/url-shortner-python/url-shortner-python'
    #     source /mnt/d/actions-runner/gh-env/bin/activate
    #     python3 -m pip install --index-url http://localhost:8081/repository/pypi-group/simple -r app/requirements.txt 

    # - name: CodeCoverage
    #   shell: bash
    #   run: |
    #     source /mnt/d/actions-runner/gh-env/bin/activate
    #     pytest --cov=app --cov-report=xml:app/coverage.xml
    
    # - name: Sonarqube Analysis
    #   run: |
    #     docker run \
    #     --rm \
    #     -e SONAR_SCANNER_OPTS="\
    #       -Dsonar.projectKey=url-shortner-python \
    #       -Dsonar.projectName=url-shortner-python \
    #       -Dsonar.projectVersion=1.0 \
    #       -Dsonar.sources=/usr/src/ \
    #       -Dsonar.host.url=http://host.docker.internal:9000 \
    #       -Dsonar.sourceEncoding=UTF-8 \
    #       -Dsonar.python.version=3.11 \
    #       -Dsonar.python.coverage.reportPaths=/usr/src/coverage.xml \
    #       -Dsonar.exclusions=**/migrations/**,k8-manifest/**,vnv-urlshrt/** \
    #       -Dsonar.coverage.exclusions=**/migrations/**,**/test_*.py \
    #       -Dsonar.token=${{ secrets.SONAR_TOKEN }}" \
    #     -v "./app:/usr/src" \
    #     sonarsource/sonar-scanner-cli
    
    # - name: SBOM Report Generation
    #   run: |
    #     syft scan dir:./app -o cyclonedx-json > sbom-cyclonedx.json

    #     #Get Project ID of D-Track
    #     PROJECT_ID=$(curl -s -X GET "http://localhost:8090/api/v1/project?name=${GITHUB_REPOSITORY##*/}" -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" | jq '.[0].uuid')

    #     # Upload SBOM Report to DTRACK
    #     curl -X POST "http://localhost:8090/api/v1/bom" -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" -H "Content-Type: multipart/form-data" -F "project=$PROJECT_ID" -F "bom=@sbom-cyclonedx.json"
    
    # - name: Vulnerability scan with Grype
    #   env:
    #     GRYPE_DB_CACHE_DIR: "/home/vrnaveenkr/.cache/grype/db/"
    #   run: |
    #     grype sbom:sbom-cyclonedx.json -o table --fail-on High -v
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'
    
    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.1.0
      env:
        DOTNET_HOST_PATH: /usr/bin/dotnet
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_NOLOGO: true
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
        GIT_VERSION_DISABLE_REPOOWNER_CHECK: true
    
    # - name: Create and Push Artifacts to Nexus
    #   run: |
    #     apt-get install zip -y
    #     zip -r ${{ steps.version_step.outputs.FullSemVer }}.zip app/

    #     # Push artifacts to Nexus
    #     curl -u admin:${{ secrets.NEXUS_PASSWORD }} \
    #     --upload-file ${{ steps.version_step.outputs.FullSemVer }}.zip \
    #     http://localhost:8081/repository/url-shortner-artifacts/${{ steps.version_step.outputs.FullSemVer }}.zip

    - name: Build Docker image
      run : |
        cd app
        docker build -t localhost:5000/url-shotner:${{ steps.version_step.outputs.FullSemVer }} .
        # docker login localhost:5000 -u admin -p ${{ secrets.NEXUS_PASSWORD }}
        # docker push localhost:5000/url-shotner:${{ steps.version_step.outputs.FullSemVer }}
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'localhost:5000/url-shotner:${{ steps.version_step.outputs.FullSemVer }}'
        format: 'json'
        output: 'trivy-results-${{ steps.version_step.outputs.FullSemVer }}.json'
    
    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-results-${{ steps.version_step.outputs.FullSemVer }}.json
        retention-days: 1

