name: Create Helm Package and Publish

on:
  workflow_dispatch:
    inputs:
      APP_RELEASE_VERSION:
        type: string
        required: true
        description: Version to be released
      ENVIRONMENT:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  create-helm-package-publish:
    runs-on: [self-hosted, macOS, ARM64, nkmac]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    
    - name: Update Helm Chart Version
      run: |
        cd deployment/helm/
        yq -i ".app.deploy.tag = \"${{ inputs.APP_RELEASE_VERSION }}\"" ./url-shortner/values.yaml
        yq -i ".appVersion = \"${{ inputs.APP_RELEASE_VERSION }}\"" ./url-shortner/Chart.yaml
        yq -i ".version = \"${{ inputs.APP_RELEASE_VERSION }}\"" ./url-shortner/Chart.yaml
    
    - name: Package and Push Helm Chart
      run: |
        helm package deployment/helm/url-shortner
        # helm plugin install https://github.com/chartmuseum/helm-push.git
        ls -lar
        helm repo add nexus-helm http://localhost:9011/repository/helm-local/ --username admin --password ${{ secrets.NEXUS_PASSWORD }}
        helm cm-push ./url-shortner-${{ inputs.APP_RELEASE_VERSION }}.tgz nexus-helm --username admin --password ${{ secrets.NEXUS_PASSWORD }} --context-path=/repository/helm-local/


        