apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels: 
    {{- include "app.labels" . | nindent 4}}
    app.kubernetes.io/component: {{ .Values.app.component }}
  name: "{{ include "app.fullname" . }}-appsvc"
spec:
  type: {{ .Values.app.svc.type }}
  ports:
  - name: {{ include "app.name" . }}
    port: {{ .Values.app.svc.port }}
    protocol: TCP
    targetPort: {{ .Values.app.svc.targetPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app.component }}
status:
  loadBalancer: {}
