apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: 
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app.component }}
  name: "{{ include "app.fullname" . }}-app"
spec:
  replicas: {{ .Values.app.deploy.replicas }}
  selector:
    matchLabels: 
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.app.component }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels: 
        {{- include "app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.app.component }}
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            MYSQL_HOST={{ include "app.fullname" . }}-mysqlsvc
            echo "Waiting for MySQL..."
            while ! nc -vz $MYSQL_HOST 3306 >/dev/null 2>&1; do
              echo "MySQL not ready, sleeping 5s..."
              sleep 5
            done
            echo "MySQL is ready!"
      containers:
      - image: "{{ .Values.app.deploy.image }}:{{ .Values.app.deploy.tag }}"
        name: "{{ include "app.fullname" . }}-app"
        ports:
          - containerPort: {{ .Values.app.deploy.containerPort }}
        env:
          - name: REDIS_HOST
            value: {{ include "app.fullname" . }}-redissvc
          - name: MYSQL_HOST
            value: {{ include "app.fullname" . }}-mysqlsvc
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.app.deploy.otel_endpoint }}
        resources: {}
status: {}
