apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ingress
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app.component }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ include "app.fullname" . }}-appsvc"
            port:
              number: {{ .Values.app.svc.port }}
