apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.redis.component }}
  name: "{{ include "app.fullname" .}}-redissvc"
spec:
  type: {{ .Values.redis.svc.type }}
  ports:
  - port: {{ .Values.redis.svc.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.svc.targetPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: {{ .Values.redis.component }}
status:
  loadBalancer: {}
